services:
  kafka:
    image: apache/kafka:3.9.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      CLUSTER_ID: "lab1-kafka-cluster-001"
    volumes:
      - kafka-data:/var/lib/kafka/data

  producer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lab1-producer
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    command: python -m src.lab1.producer --delay 0.05
    volumes:
      - ./data:/app/data:ro
    profiles:
      - lab1

  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lab1-consumer
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    command: python -m src.lab1.consumer
    volumes:
      - ./output:/app/output
      - ./checkpoints:/app/checkpoints
    profiles:
      - lab1

volumes:
  kafka-data:
